### PR TITLE
Static build automation

### PR DESCRIPTION
**Pull request by ChristophWurst**
Test build can be seen at https://github.com/ChristophWurst/kitinerary-bin/actions/runs/7101600709/job/19330067775?pr=9.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> -- No package 'nss' found

@vkrause is that a missing dependency in the centos setup script of https://invent.kde.org/pim/kitinerary/?

**Comment by vkrause** [comment]
> > -- No package 'nss' found
> 
> @vkrause is that a missing dependency in the centos setup script of https://invent.kde.org/pim/kitinerary/?

This indeed needed a few adjustment for changes in various dependencies, sorry about that. Should be fixed once https://invent.kde.org/pim/kitinerary/-/merge_requests/85 integrates, there are working artifacts in the test run here: https://invent.kde.org/pim/kitinerary/-/jobs/1419920.

**Comment by ChristophWurst** [comment]
No worries. Thanks a lot for looking into this!

**Comment by ChristophWurst** [comment]
> git clone https://invent.kde.org/-DKITINERARY_STANDALONE_CLI_EXTRACTOR=ON  -DKITINERARY_STANDALONE_CLI_EXTRACTOR=ON
> error: unknown switch `D'

https://github.com/ChristophWurst/kitinerary-bin/actions/runs/7035352519/job/19298309629?pr=9#step:4:19731

**Comment by ChristophWurst** [comment]
CI_PROJECT_PATH is not set on github CI

https://github.com/KDE/kitinerary/blob/3364e192d073fe2b25e638dc9aaac6a29a38ca3c/scripts/build-cmake-modules.sh#L91

**Comment by ChristophWurst** [comment]
There is no `git` in the centos image. The checkout action has a fallback for the github REST API. The pull request action fails.

**Comment by vkrause** [comment]
> There is no `git` in the centos image. The checkout action has a fallback for the github REST API. The pull request action fails.

Not in the base image, yes, as that's too old to talk to any half-way current Git server. A working version of git is installed via the "rh-git227" package and activated by the `source /opt/rh/rh-git227/enable` line.

Yes, this is all incredibly cumbersome and painful, but unfortunately that's the price we have to pay for still supporting ancient glibc versions :(

**Comment by ChristophWurst** [comment]
> Not in the base image, yes, as that's too old to talk to any half-way current Git server. A working version of git is installed via the "rh-git227" package and activated by the `source /opt/rh/rh-git227/enable` line.

I've just realized that this was the case already

**Comment by ChristophWurst** [comment]
git227 might be too old for the pr action

> Prepare git configuration
>  /usr/bin/git config --global --name-only --get-regexp safe.directory /__w/kitinerary-bin/kitinerary-bin/kitinerary-bin
>  error: unknown option `name-only'

**Comment by ChristophWurst** [comment]
> Error: When the repository is checked out on a commit instead of a branch, the 'base' input must be supplied.

expected on this feature branch. this should work on main.

**Comment by ChristophWurst** [comment]
@vkrause should I check out a specific git reference when I want to build the tool for bundling? If I go with the default branch, it could be a developer snapshot. I see you are tagging releases at https://invent.kde.org/pim/kitinerary/-/tags.

**Comment by kesselb** [comment]
Yeah, you made it work :partying_face:

**Comment by ChristophWurst** [comment]
~~I'm struggling to install rh-git227 and keep it active across github action steps. I want to install git, check out the repo, check out the latest release tag, then build and finally create a PR.~~

Edit: works

**Comment by vkrause** [comment]
> @vkrause should I check out a specific git reference when I want to build the tool for bundling? If I go with the default branch, it could be a developer snapshot. I see you are tagging releases at https://invent.kde.org/pim/kitinerary/-/tags.

IMHO we should eventually use proper releases for this indeed. That however not only goes for the extractor itself, but also for the dependencies it pulls in, otherwise we'll end up with the same situation we just had that changes in the dependencies break past release builds again. I'll work on changing that upstream accordingly.

We can then either backport that to the last stable release (23.08.x series), or do that for the next major release planned for February 2024, whichever you prefer.

**Comment by ChristophWurst** [comment]
Git tags are fine for me. I found `git describe --abbrev=0 --tags --match=v*.*.*` to give me the latest release tag.

Right now I'm using `git describe --tags --match=v*.*.*` in the automation because the last release doesn't build.

The build/release pipeline is only semi automatic. I can still give updates a quick test before I send them to production. So I'm fine with using an intermediate version for now and jump to stable releases in February.

**Comment by vkrause** [comment]
Great! The upstream build scripts now use the latest releases of all external dependencies. Updating that as well as  properly setting versions for internal dependencies on branching will then become part of the release chores there.

**Pull request merged**
